version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12.x
    commands:
      - npm install -g yarn
  pre_build:
    commands:
      - yarn install --quiet
      - yarn global add serverless --quiet

  build:
    commands:
      - yarn build
      - serverless deploy

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: build

cache:
  paths:
    - 'node_modules/**/*'
